apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  {{ $nameG := print  .Values.meta.env "-" .Values.baseName.gateway -}}
  name: {{ $nameG }}
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    istio: ingressgateway
  # gatewayClassName: istio-gateway-class
  gatewayClassName: istio
  listeners:
  - protocol: HTTP
    port: 80
    name: {{ $nameG }}-protocol-http
    # allowedRoutes:
    #   namespaces:
    #     from: Same  
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  labels:
    gateway: {{ $nameG }}  
spec:
  parentRefs:
  - name: {{ $nameG }}  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /keycloak
  - backendRefs:
    - name: keycloak
      port: 80


