apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
    # - 192.168.0.100/32
    - 192.168.0.102/32
    - 192.168.0.103/32
    # - 192.168.0.100-192.168.0.103
  autoAssign: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool

