apiVersion: v1
kind: ConfigMap
metadata:
  {{ $relname := .Release.Name -}}
  name: {{ required "required values meta.env" .Values.meta.env }}-{{ $relname }}-configmap
  labels:
  {{- range $key, $val := .Values.labels.configmap }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}  
data:
  myvalue: "Hello World"

  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $relname }}
  
  {{- if eq .drink "beer" }}
  mug: "false"
  {{- else }}
  mug: "true" 
  {{- end }}  

  {{- end }}
  # The |- marker in YAML takes a multi-line string. 
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }} 
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{ $index }}: {{ $topping | title | quote  }}
    {{- end }}    