apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: nginx
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: {{ .Release.Namespace}}
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.25.4
          name: nginx
          ports:
            - name: web
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: {{ .Release.Namespace}}
spec:
  # ingressClassName: {{ .Values.ingressClassName }}
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      # - path: /keycloak/(.*)
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
      
